// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_9-KidqLpJ5LRMmBxHkWC14g-rraaQA',
    appId: '1:882693671474:web:1f8c283fcefac2af9c8a2b',
    messagingSenderId: '882693671474',
    projectId: 'collectly-6469a',
    authDomain: 'collectly-6469a.firebaseapp.com',
    storageBucket: 'collectly-6469a.appspot.com',
    measurementId: 'G-6BSZN4CF13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4zUzQnjJr_6RF2PK-YTw5Md__COGSzWo',
    appId: '1:882693671474:android:7cd1cdc705f9aa7f9c8a2b',
    messagingSenderId: '882693671474',
    projectId: 'collectly-6469a',
    storageBucket: 'collectly-6469a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstxCtMqcM8noQB_diYdfHZHr3nxhBfK4',
    appId: '1:882693671474:ios:36f54041d91604f39c8a2b',
    messagingSenderId: '882693671474',
    projectId: 'collectly-6469a',
    storageBucket: 'collectly-6469a.appspot.com',
    iosClientId: '882693671474-nvn0t78dsc8evagq21blrv2b51eicpms.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstxCtMqcM8noQB_diYdfHZHr3nxhBfK4',
    appId: '1:882693671474:ios:36f54041d91604f39c8a2b',
    messagingSenderId: '882693671474',
    projectId: 'collectly-6469a',
    storageBucket: 'collectly-6469a.appspot.com',
    iosClientId: '882693671474-nvn0t78dsc8evagq21blrv2b51eicpms.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectlyApp',
  );
}
